# Generated by Django 4.2.11 on 2024-04-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_tags', to='banners.banner')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.feature')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.tag')),
            ],
            options={
                'unique_together': {('tag', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banners.feature'),
        ),
        migrations.AddField(
            model_name='banner',
            name='tags',
            field=models.ManyToManyField(related_name='banners', through='banners.BannerTag', to='banners.tag'),
        ),
    ]
